### ISSUE TITLE
async process objects' stdout and stderr are not StreamReaders when using PIPE

### ISSUE THREAD

**Issue by jranieri-grammatech** [aklajnert/pytest-subprocess#65]
According to the [asyncio.subprocess.PIPE docs](https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.asyncio.subprocess.PIPE):
> If PIPE is passed to stdin argument, the Process.stdin attribute will point to a StreamWriter instance.
>
> If PIPE is passed to stdout or stderr arguments, the Process.stdout and Process.stderr attributes will point to StreamReader instances.

It looks like the object that fake_subprocess returns from `create_process_exec` (and probably `create_process_shell`) don't mimic this correctly. Here's an example test:
```python
import asyncio
import os

def test_stdio_and_stderr(fake_process):
    async def impl():
        process = await asyncio.create_subprocess_exec(
            "ls", "/",
            stdin=open(os.devnull, "r"), # work around #64
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        # wait for the process
        async def _read_stream(
            stream: asyncio.StreamReader, logtype: str,
        ):
            while True:
                line = await stream.readline()
                if not line:
                    break
                # do something with line

        await asyncio.wait(
            [
                asyncio.create_task(
                    _read_stream(process.stdout, "stdout")
                ),
                asyncio.create_task(
                    _read_stream(process.stderr, "stderr")
                ),
                asyncio.create_task(process.wait()),
            ]
        )

    fake_process.register_subprocess(["ls", "/"], stdout=[b"one", b"two"])
    asyncio.get_event_loop().run_until_complete(impl())

    # Force pytest to display the asyncio exception messages
    assert False
```

The expected output is for there to be a failed assertion -- but nothing else. Here's the actual output:
```
------------------------------------------- Captured log call --------------------------------------------
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-2' coro=<test_stdio_and_stderr.<locals>.impl.<locals>._read_stream() done, defined at /elm0/jranieri/src/gtirb-server2/server/test/test_stdio.py:15> exception=TypeError("object bytes can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/elm0/jranieri/src/gtirb-server2/server/test/test_stdio.py", line 19, in _read_stream
    line = await stream.readline()
TypeError: object bytes can't be used in 'await' expression
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-3' coro=<test_stdio_and_stderr.<locals>.impl.<locals>._read_stream() done, defined at /elm0/jranieri/src/gtirb-server2/server/test/test_stdio.py:15> exception=TypeError("object bytes can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/elm0/jranieri/src/gtirb-server2/server/test/test_stdio.py", line 19, in _read_stream
    line = await stream.readline()
TypeError: object bytes can't be used in 'await' expression
======================================== short test summary info =========================================
FAILED test_stdio.py::test_stdio_and_stderr - assert False
```

**Comment by aklajnert** [comment]
Thanks for the report, I'll try to fix it soon, but I'm a bit busy right now. Feel free to submit a PR with the fix.
